version: '3.1'
services:
  minio:
    image: quay.io/minio/minio
    container_name: 'minio_container'
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: :WsJX[|%KR(8a)ls5FCk
    command: server /data --console-address ":9001"
